# # base go image
# FROM golang:1.18-alpine as builder

# RUN mkdir /app

# COPY . /app

# WORKDIR /app

# RUN CGO_ENABLED=0 go build -o brokerApp ./cmd/api

# RUN chmod +x /app/brokerApp

# # build a tiny docker image
FROM alpine:latest

RUN mkdir /app

COPY goRestApp /app
COPY env-docker /app/.env

CMD [ "/app/goRestApp"]